version: '3'
services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - mynet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiii-proekt
    depends_on:
      - db   
    ports:
      - "9090:9090"  
    networks:
      - mynet

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres-data:

networks:
  mynet:
    driver: bridge